### ISSUE TITLE
leaflet and reactable on smaller width devices

### ISSUE THREAD

**Issue by timelyportfolio** [urbanSpatial/COVIDPlanning#1]
@mrecos, I think the table looks nice.  I made some improvements in the package that will help us cut down data size and also render more quickly on sort.  I will submit a pull request to make the change.

I noticed if we simulate a small width device we can see that the map and table will extend beyond their natural boundaries.  I believe we can fix with a `maxWidth` in our CSS around [lines](https://github.com/urbanSpatial/COVIDPlanning/blob/master/index.rmd#L87-L95)

```
.leaflet-container, .reactable {
  max-width: 98vw;  /* could also use % or even more precise calc(100vw - 40px)*/
}
```

![image](https://user-images.githubusercontent.com/837910/87037918-9d8fae00-c1b2-11ea-92d2-2b38f3d8a4fe.png)

**Comment by mrecos** [comment]
Thanks @timelyportfolio! I'll add to this that the text on the landing page is too narrow on mobile b/c of my use of absolute pixels for `p{}` on the line linked below. Perhaps the relative scaling would work there as well?
https://github.com/urbanSpatial/COVIDPlanning/blob/018dafcb685c3a20fe2cd023cca854fe8e2e9967/index.rmd#L97

I sent you the required data to knit the index.rmd. If you can implement those suggestions locally, then submit a PR and we'll merge.

**Comment by mrecos** [comment]
Hello @timelyportfolio , does the commit 2b0fcdc14de075df7375488817ef35ad03048dfb and the merge above close this issue?

**Comment by timelyportfolio** [comment]
yes I believe so

**Comment by mrecos** [comment]
adding merge #3 to the resolution of this issue.
