### ISSUE TITLE
reactable histograms

### ISSUE THREAD

**Issue by timelyportfolio** [urbanSpatial/COVIDPlanning#5]
@mrecos 

Do we want to add tooltips to the reactable histograms?

Is something wrong with the grants histograms?

**Comment by timelyportfolio** [comment]
There is one outlier of $250,000 that is causing the problem.  My "solution" is to ignore. This is not technically correct, but for these purposes I think the information of all grants less than the one $250,000 is outlier is valuable.  I'm not sure how to communicate the $250,000 though to the user.

   0 | 00000000000000000000000000000000000000000000000000000000000000000000+2010
   2 | 00000000000000000000000000000000000000000000000000000000000000000000+101
   4 | 222355555555500000558
   6 | 0
   8 | 
  10 | 
  12 | 
  14 | 
  16 | 
  18 | 
  20 | 
  22 | 
  24 | 0

**Comment by mrecos** [comment]
@timelyportfolio thank you for this solution. I agree that the visual of the smaller grants is important for this table. That large grant is referenced in the County level reports. Thanks!
